# Use a minimal Python image
FROM python:3.9-slim

# Set working directory inside the container
WORKDIR /app

# Copy HTML file into the container
COPY . .

# Expose port 8000
EXPOSE 8000

# Run Python's built-in HTTP server
CMD ["python3", "-m", "http.server", "8000"]


# docker build -t static-site .
# docker run -d -p 8080:8000 static-site
